services:
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD} 
    env_file:
      - .env 
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"

  dagster:
    build:
      context: .
      dockerfile: .dagster/dockerfile
    restart: always
    environment:
      - name=value
    volumes:
      - hostPath:containerPath:ro
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - minio
      - dbt
    
    dbt:
      build:
        context: . 
        dockerfile: ./dbt-project/docker

    

