services:
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    env_file:
      - .env
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  dagster:
    build:
      context: .
      dockerfile: ./dagster_loc/Dockerfile
    restart: always
    environment:
      - MINIO_USER=${MINIO_USER}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_BUCKET=nike-data
      - DB_PATH=/data/nike_warehouse.duckdb
      - DAGSTER_HOME=/app/dagster_loc
      - PYTHONPATH=/app
    volumes:
      - ./data-generator:/app/data-generator
      - ./dagster_loc:/app/dagster_loc
      - ./dbt_project:/app/dbt_project
      - duckdb_data:/data
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      minio:
        condition: service_healthy
      dbt:
        condition: service_started
    command: dagster dev -h 0.0.0.0 -p 3000 -m dagster_loc.repository

  dbt:
    build:
      context: ./dbt_project
      dockerfile: Dockerfile
    restart: always
    environment:
      - MINIO_USER=${MINIO_USER}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
      - MINIO_ENDPOINT=http://minio:9000
    volumes:
      - ./dbt_project:/dbt
      - duckdb_data:/data
    depends_on:
      minio:
        condition: service_healthy

  # metabase:
  #   image: 'metabase/metabase:latest'
  #   restart: always
  #   ports:
  #     - "4000:3000"
  #   volumes:
  #     - duckdb_data:/data
  #     - metabase_data:/metabase-data
  #   environment:
  #     - MB_DB_TYPE=h2
  #   depends_on:
  #     - dagster
  #     - dbt

  metabase:
    build:
      context: .
      dockerfile: Dockerfile.metabase
    restart: always
    ports:
      - "4000:3000"
    volumes:
      - duckdb_data:/data
      - metabase_data:/metabase-data
    environment:
      - MB_DB_TYPE=h2
      - MB_DB_FILE=/metabase-data/metabase.db
      - MB_PLUGINS_DIR=/home/plugins/
    depends_on:
      - dagster
      - dbt

volumes:
  minio_data:
  duckdb_data:
  metabase_data: