FROM openjdk:19-buster

ENV MB_PLUGINS_DIR=/home/plugins/

ADD https://downloads.metabase.com/v0.52.4/metabase.jar /home/metabase.jar

RUN mkdir -p /home/plugins/

# manually downloaded the duckdb driver
COPY metabase/duckdb.metabase-driver.jar /home/plugins/ 

RUN chmod 744 /home/plugins/duckdb.metabase-driver.jar

CMD ["java", "-jar", "/home/metabase.jar"]
