name: 'nike_market_pipeline'
version: '1.0.0'
config-version: 2

profile: 'nike_market_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  nike_market_pipeline:
    materialized: table
    staging:
      materialized: view
    intermediate:
      materialized: view
    marts:
      materialized: table 