nike_market_pipeline:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /data/nike_market.duckdb
      threads: 4
      extensions:
        - parquet
        - httpfs
      external_root: 's3://nike-data'  # MinIO bucket
      settings:
        s3_endpoint: 'minio:9000'  # Docker service name
        s3_access_key_id: '{{ env_var("MINIO_USER") }}'
        s3_secret_access_key: '{{ env_var("MINIO_PASSWORD") }}'
        s3_use_ssl: false
        s3_url_style: 'path'

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4
